#!/usr/bin/Rscript

#Script to automatically create the quality control plots from HOMER.

#Parse command line parameters
args <- commandArgs(trailingOnly = TRUE)

if(length(args) < 1) {
	write("Wrong usage!", stderr())
	write("Rscript create_quality_control_plots.R <directory with files generated by homer>", stderr())
	quit()
}

#Check if all files exists
if(!file.exists(paste(args, "tagCountDistribution.txt", sep=""))) {
	write("File tagCountDistribution is missing!", stderr())
	write("Exiting programm", stderr())
	quit()
} else if(!file.exists(paste(args, "tagAutocorrelation.txt", sep=""))) {
	write("File tagAutocorrelation.txt is missing!", stderr())
	write("Exiting programm", stderr())
	quit()
} else if(!file.exists(paste(args, "tagFreq.txt", sep=""))) {
	write("File tagFreq.txt is missing!", stderr())
	write("Exiting programm", stderr())
	quit()
} else if(!file.exists(paste(args, "genomeGCcontent.txt", sep=""))) {
	write("File genomeGCcontent.txt is missing!", stderr())
	write("Exiting programm", stderr())
	quit()
} else if(!file.exists(paste(args, "tagGCcontent.txt", sep=""))) {
	write("File tagGCcontent.txt is missing!", stderr())
	write("Exiting programm", stderr())
	quit()
} else {
	write("Found all files!", stderr())
	write("Creating plots", stderr())
}


#Define output file
save_file = paste(args, "statistics.pdf", sep="")
pdf(file=save_file, height=13, width=12)
par(mfrow=c(4,2))
par(mar=c(5,6,2,0.1))

#Plot clonal tag distribution
dist_path <- paste(args, "tagCountDistribution.txt", sep="")
dist <- read.table(dist_path, skip=1)
barplot(tail(head(dist[,2], n=11), n=10), ylab="Fraction", col=c("blue"), names.arg=c(1:10), ylim=c(0,1), xlab="Number of Reads", main="Clonal Tag Distribution")
abline(h=seq(0,1,0.1), col=c("gray"))
par(new=T)
barplot(tail(head(dist[,2], n=11), n=10), ylab="Fraction", col=c("blue"), names.arg=c(1:10), ylim=c(0,1), xlab="Number of Reads", main="Clonal Tag Distribution")

#Plot Autocorrelation
auto_path <- paste(args, "tagAutocorrelation.txt", sep="")
auto <- read.table(auto_path, skip=1)

#find max value in both strands
if(max(auto[,2]) < max(auto[,3])) {
	max_value <- max(auto[,3])
} else {
	max_value <- max(auto[,2])
}

#define the points for abline
one_digit <- max_value/(10**(nchar(max_value) - 1))
one_digit_int <- round(one_digit)
final_point <- one_digit_int * (10**(nchar(max_value) - 1))

#Plot
plot(auto[,1], auto[,2], type="l", col="red", ylim=c(0,max_value), main="Autocorrelation", xlab="Distance from reference tag (bp)", ylab="Number of observations")
abline(h=seq(0, max_value, (final_point/4)), col=c("grey"))
abline(v=seq(-2000, 2000, 500), col=c("grey"))
par(new=T)
plot(auto[,1], auto[,2], type="l", col="red", ylim=c(0,max_value), main="Autocorrelation", xlab="Distance from reference tag (bp)", ylab="Number of observations")
lines(auto[,1], auto[,3], type="l", col="blue")
legend("topleft", c("Same Strand", "Opposite strand"), col=c("red", "blue"), pch=15)

#Plot sequence bias
freq_path <- paste(args, "tagFreq.txt", sep="")
freq <- read.table(freq_path, header=TRUE)
plot(freq[,1], freq[,2], type="l", col="blue", ylim=c(0,0.45), xlab="Position", ylab="Fraction", main="Sequence bias", lwd=1.5)
abline(h=seq(0,0.5,0.05), v=seq(-50,200,50), col=c("grey"))
par(new=T)
plot(freq[,1], freq[,2], type="l", col="blue", ylim=c(0,0.45), xlab="Position", ylab="Fraction", main="Sequence bias", lwd=2)
lines(freq[,1], freq[,3], col="darkorange", lwd=2)
lines(freq[,1], freq[,4], col="gold", lwd=2)
lines(freq[,1], freq[,5], col="green4", lwd=2)
legend("topright", c("A", "C", "G", "T"), col=c("blue", "darkorange", "gold", "green4"), pch=15)

#Plot GC Distribution
frag_genome <- paste(args, "genomeGCcontent.txt", sep="")
frag_tag <- paste(args, "tagGCcontent.txt", sep="")
genome <- read.table(frag_genome, skip=1)
tag <- read.table(frag_tag, skip=1)

if(max(tag[,3]) > max(genome[,3])) {
	max_value <- max(tag[,3])
} else {
	max_value <- max(genome[,3])
}
plot(genome[,1], tag[,3], type="l", ylim=c(0, max_value), col="red", xlab="GC content", ylab="Normalized fraction", main="Fragment GC% Distribution")
abline(v=seq(0,1,0.1), h=seq(0,max_value,1), col=c("grey"))
par(new=T)
plot(genome[,1], tag[,3], type="l", ylim=c(0, max_value), col="red", xlab="GC content", ylab="Normalized fraction", main="Fragment GC% Distribution")
lines(genome[,1], genome[,3], col="blue")
legend("topleft", c("Genome", "Tag"), col=c("blue", "red"), pch=15)

dev.off()
write("Plot successfully created", stderr())
write(paste("Plot located in: ", args, "statistics.pdf", sep=""), stderr())
